import './globals.css'
import React from 'react'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import { ReduxProvider } from '@/components/redux/provider'
import { MUIProvider } from '@/components/MUI/MUIProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="initial-scale=1, width=device-width" />
      </head>
      <body className={inter.className}>
          <MUIProvider>
            <ReduxProvider>
              {children}
            </ReduxProvider>
          </MUIProvider>
      </body>
    </html>
  )
}
